import type { ChatSession } from './types.js';
import type { Broadcast } from './timerManager.js';
import { getProvider, getProviderIdentityNote } from './aiProvider.js';
import type { AIMessage } from './aiProvider.js';

const chatSessions = new Map<string, ChatSession>();
let chatCounter = 0;

// Track session IDs generated by chat so fileWatcher can exclude them
const chatSessionIds = new Set<string>();

// Map chatId → agentId for the pixel character on the map
const chatAgentIds = new Map<string, number>();

export function isChatSessionId(sessionId: string): boolean {
	return chatSessionIds.has(sessionId);
}

export function initChatManager(ref: { current: number }): void {
	nextAgentIdRef = ref;
}

let nextAgentIdRef: { current: number } = { current: 1000 };

export function createChat(cwd: string, broadcast: Broadcast): string {
	const chatId = `chat-${++chatCounter}`;

	const session: ChatSession = {
		chatId,
		cwd,
		activeProcess: null,
		activeGeneration: null,
		history: [],
	};

	chatSessions.set(chatId, session);

	// Create a pixel character on the map for this chat
	const agentId = nextAgentIdRef.current++;
	chatAgentIds.set(chatId, agentId);

	console.log(`[Chat] Created chat ${chatId} (agent ${agentId})`);
	broadcast({ type: 'chatCreated', chatId, agentId });
	broadcast({ type: 'agentCreated', id: agentId });
	return chatId;
}

const MAX_HISTORY_CHARS = 14000; // ~4,000 tokens — sliding window budget

/** Truncate history with a sliding-window character budget. */
function truncateHistory(history: Array<{ role: string; content: string }>): Array<{ role: string; content: string }> {
	if (history.length === 0) return [];

	let charBudget = MAX_HISTORY_CHARS;
	const selected: Array<{ role: string; content: string }> = [];

	// Always keep the first user message (original context)
	if (history.length > 2 && history[0].role === 'user') {
		selected.push(history[0]);
		charBudget -= history[0].content.length;
	}

	const startIdx = selected.length > 0 ? 1 : 0;
	const recent: Array<{ role: string; content: string }> = [];
	for (let i = history.length - 1; i >= startIdx; i--) {
		const msg = history[i];
		if (msg.content.length > charBudget) {
			recent.unshift({
				role: msg.role,
				content: msg.content.slice(0, Math.max(500, charBudget)) + '\n...(截斷)',
			});
			break;
		}
		charBudget -= msg.content.length;
		recent.unshift(msg);
		if (charBudget <= 0) break;
	}

	return [...selected, ...recent];
}

export function sendMessage(chatId: string, message: string, broadcast: Broadcast): void {
	const session = chatSessions.get(chatId);
	if (!session) {
		broadcast({ type: 'chatError', chatId, error: 'Chat session not found' });
		return;
	}

	if (session.activeGeneration) {
		broadcast({ type: 'chatError', chatId, error: 'Previous message still processing' });
		return;
	}

	// Build structured messages with truncated history BEFORE adding new message
	const identityNote = getProviderIdentityNote();
	const messages: AIMessage[] = [];
	if (identityNote) {
		messages.push({ role: 'system', content: identityNote.trim() });
	}
	const truncated = truncateHistory(session.history);
	for (const msg of truncated) {
		messages.push({ role: msg.role as 'user' | 'assistant' | 'system', content: msg.content });
	}
	messages.push({ role: 'user', content: message });

	// Record user message in history
	session.history.push({ role: 'user', content: message });

	// Update agent status to "active" and show alert bubble
	const agentId = chatAgentIds.get(chatId);
	if (agentId !== undefined) {
		broadcast({ type: 'agentStatus', id: agentId, status: 'active' });
		broadcast({ type: 'chatAlertBubble', chatId, agentId });
	}

	// Throttle stream chunks to avoid overwhelming the UI (especially with fast SSE providers)
	let chunkBuffer = '';
	let chunkTimer: ReturnType<typeof setTimeout> | null = null;
	const CHUNK_INTERVAL = 80; // ms
	const flushChunks = () => {
		if (chunkBuffer) {
			broadcast({ type: 'chatStreamChunk', chatId, text: chunkBuffer });
			chunkBuffer = '';
		}
		chunkTimer = null;
	};

	const provider = getProvider();
	const handle = provider.generate(messages, {
		onTextChunk: (text) => {
			chunkBuffer += text;
			if (!chunkTimer) {
				chunkTimer = setTimeout(flushChunks, CHUNK_INTERVAL);
			}
		},
		onThinkingChunk: (text) => {
			if (agentId !== undefined) {
				broadcast({ type: 'chatThinkingChunk', chatId, agentId, text });
			}
		},
	}, {
		cwd: session.cwd,
	});

	session.activeGeneration = handle;

	handle.done.then((response) => {
		if (response) {
			session.history.push({ role: 'assistant', content: response });
		}
	}).catch((err) => {
		// Suppress internal session conflict errors — don't show to user
		if (err instanceof Error && err.message.includes('already in use')) {
			console.log(`[Chat ${chatId}] Session ID conflict (suppressed)`);
			return;
		}
		console.error(`[Chat ${chatId}] Error:`, err.message);
		broadcast({ type: 'chatError', chatId, error: err.message });
	}).finally(() => {
		// Flush any remaining throttled chunks
		if (chunkTimer) clearTimeout(chunkTimer);
		flushChunks();

		session.activeGeneration = null;

		const agId = chatAgentIds.get(chatId);
		if (agId !== undefined) {
			broadcast({ type: 'agentStatus', id: agId, status: 'waiting' });
			broadcast({ type: 'chatStreamEnd', chatId, agentId: agId });
			setTimeout(() => {
				broadcast({ type: 'agentStatus', id: agId, status: 'idle' });
			}, 3000);
		} else {
			broadcast({ type: 'chatStreamEnd', chatId, agentId: -1 });
		}
	});
}

export function closeChat(chatId: string, broadcast: Broadcast): void {
	const session = chatSessions.get(chatId);
	if (!session) return;

	if (session.activeGeneration) {
		try {
			session.activeGeneration.abort();
		} catch { /* generation may already be done */ }
	}

	// Remove the pixel character from the map
	const closedAgentId = chatAgentIds.get(chatId);
	if (closedAgentId !== undefined) {
		broadcast({ type: 'agentClosed', id: closedAgentId });
		chatAgentIds.delete(chatId);
	}

	chatSessions.delete(chatId);
	console.log(`[Chat] Closed chat ${chatId}`);
	broadcast({ type: 'chatClosed', chatId });
}

export function getExistingChatIds(): string[] {
	return Array.from(chatSessions.keys());
}

export function getChatAgentIds(): number[] {
	return Array.from(chatAgentIds.values());
}

export function closeAllChats(broadcast: Broadcast): void {
	for (const chatId of chatSessions.keys()) {
		closeChat(chatId, broadcast);
	}
}
