import { spawn } from 'child_process';
import type { ChatSession } from './types.js';
import type { Broadcast } from './timerManager.js';

const chatSessions = new Map<string, ChatSession>();
let chatCounter = 0;

// Track session IDs generated by chat so fileWatcher can exclude them
const chatSessionIds = new Set<string>();

// Map chatId → agentId for the pixel character on the map
const chatAgentIds = new Map<string, number>();

export function isChatSessionId(sessionId: string): boolean {
	return chatSessionIds.has(sessionId);
}

export function initChatManager(ref: { current: number }): void {
	nextAgentIdRef = ref;
}

let nextAgentIdRef: { current: number } = { current: 1000 };

export function createChat(cwd: string, broadcast: Broadcast): string {
	const chatId = `chat-${++chatCounter}`;

	const session: ChatSession = {
		chatId,
		cwd,
		activeProcess: null,
		history: [],
	};

	chatSessions.set(chatId, session);

	// Create a pixel character on the map for this chat
	const agentId = nextAgentIdRef.current++;
	chatAgentIds.set(chatId, agentId);

	console.log(`[Chat] Created chat ${chatId} (agent ${agentId})`);
	broadcast({ type: 'chatCreated', chatId });
	broadcast({ type: 'agentCreated', id: agentId });
	return chatId;
}

/**
 * Build a prompt that includes conversation history for context.
 * The current user message should NOT yet be in session.history when this is called.
 */
function buildPromptWithHistory(history: Array<{ role: string; content: string }>, newMessage: string): string {
	if (history.length === 0) {
		return newMessage;
	}
	const lines = history.map((m) =>
		m.role === 'user' ? `Human: ${m.content}` : `Assistant: ${m.content}`,
	);
	return `${lines.join('\n')}\nHuman: ${newMessage}\n\nContinue the conversation above. Respond to the latest Human message only.`;
}

export function sendMessage(chatId: string, message: string, broadcast: Broadcast): void {
	const session = chatSessions.get(chatId);
	if (!session) {
		broadcast({ type: 'chatError', chatId, error: 'Chat session not found' });
		return;
	}

	if (session.activeProcess) {
		broadcast({ type: 'chatError', chatId, error: 'Previous message still processing' });
		return;
	}

	// Build prompt BEFORE adding to history (to avoid duplication)
	const fullPrompt = buildPromptWithHistory(session.history, message);

	// Now record user message in history
	session.history.push({ role: 'user', content: message });

	// Strip CLAUDECODE env var to avoid "cannot be launched inside another Claude Code session" error
	const cleanEnv = { ...process.env };
	delete cleanEnv.CLAUDECODE;

	// Spawn claude in print mode, reading prompt from stdin to avoid shell escaping issues
	// --no-session-persistence: don't write session files (avoids session locks)
	// --verbose is required for --output-format stream-json with -p
	// stdin is 'pipe' — we write the prompt and immediately close it
	const proc = spawn('claude', [
		'-p',
		'--no-session-persistence',
		'--output-format', 'stream-json',
		'--verbose',
	], {
		cwd: session.cwd,
		shell: true,
		stdio: ['pipe', 'pipe', 'pipe'],
		env: cleanEnv,
	});

	// Write prompt via stdin and close — avoids Windows shell escaping issues with Unicode
	proc.stdin.write(fullPrompt);
	proc.stdin.end();

	session.activeProcess = proc;

	// Update agent status to "active" on the map (character starts working)
	const agentId = chatAgentIds.get(chatId);
	if (agentId !== undefined) {
		broadcast({ type: 'agentStatus', id: agentId, status: 'active' });
	}

	let stdoutBuffer = '';
	let sentFromDeltas = false;
	let assistantResponse = '';

	proc.stdout.on('data', (data: Buffer) => {
		stdoutBuffer += data.toString();

		// Process complete lines (stream-json outputs one JSON per line)
		const lines = stdoutBuffer.split('\n');
		stdoutBuffer = lines.pop() || ''; // Keep incomplete line in buffer

		for (const line of lines) {
			if (!line.trim()) continue;
			try {
				const parsed = JSON.parse(line);

				// Track the session ID so fileWatcher can exclude chat-generated JSONL files
				if (parsed.type === 'system' && parsed.session_id) {
					chatSessionIds.add(parsed.session_id);
				}

				// stream-json format emits multiple message types:
				// - content_block_delta: incremental text chunks (streaming)
				// - assistant: complete message with all content blocks
				// - result: final summary (duplicates assistant text, skip to avoid double-send)
				if (parsed.type === 'content_block_delta' && parsed.delta?.text) {
					const text = parsed.delta.text;
					broadcast({ type: 'chatStreamChunk', chatId, text });
					assistantResponse += text;
					sentFromDeltas = true;
				} else if (parsed.type === 'assistant' && parsed.message?.content) {
					if (!sentFromDeltas) {
						for (const block of parsed.message.content) {
							if (block.type === 'text' && block.text) {
								broadcast({ type: 'chatStreamChunk', chatId, text: block.text });
								assistantResponse += block.text;
							}
						}
					} else {
						// Extract full text for history even if we already streamed deltas
						for (const block of parsed.message.content) {
							if (block.type === 'text' && block.text) {
								assistantResponse = block.text;
							}
						}
					}
				}
				// Skip 'result' type — it duplicates the assistant message text
			} catch {
				// Not valid JSON, might be raw text — send as-is
				broadcast({ type: 'chatStreamChunk', chatId, text: line });
				assistantResponse += line;
			}
		}
	});

	proc.stderr.on('data', (data: Buffer) => {
		const text = data.toString();
		if (text.trim()) {
			console.log(`[Chat ${chatId}] stderr: ${text.trim()}`);
		}
	});

	proc.on('error', (err) => {
		console.error(`[Chat ${chatId}] Process error:`, err.message);
		session.activeProcess = null;
		broadcast({ type: 'chatError', chatId, error: err.message });
	});

	proc.on('exit', (code) => {
		// Flush any remaining buffer
		if (stdoutBuffer.trim()) {
			try {
				const parsed = JSON.parse(stdoutBuffer);
				if (parsed.type === 'content_block_delta' && parsed.delta?.text) {
					broadcast({ type: 'chatStreamChunk', chatId, text: parsed.delta.text });
					assistantResponse += parsed.delta.text;
				} else if (parsed.type === 'assistant' && parsed.message?.content && !sentFromDeltas) {
					for (const block of parsed.message.content) {
						if (block.type === 'text' && block.text) {
							broadcast({ type: 'chatStreamChunk', chatId, text: block.text });
							assistantResponse += block.text;
						}
					}
				}
			} catch {
				if (stdoutBuffer.trim()) {
					broadcast({ type: 'chatStreamChunk', chatId, text: stdoutBuffer });
					assistantResponse += stdoutBuffer;
				}
			}
		}

		// Save assistant response to history for future context
		if (assistantResponse.trim()) {
			session.history.push({ role: 'assistant', content: assistantResponse.trim() });
		}

		session.activeProcess = null;
		if (code !== 0 && code !== null) {
			console.log(`[Chat ${chatId}] Process exited with code ${code}`);
		}

		// Clear agent active status (back to idle on the map)
		const agId = chatAgentIds.get(chatId);
		if (agId !== undefined) {
			broadcast({ type: 'agentStatus', id: agId, status: 'idle' });
		}

		broadcast({ type: 'chatStreamEnd', chatId });
	});
}

export function closeChat(chatId: string, broadcast: Broadcast): void {
	const session = chatSessions.get(chatId);
	if (!session) return;

	if (session.activeProcess) {
		try {
			session.activeProcess.kill('SIGTERM');
		} catch { /* process may already be dead */ }
	}

	// Remove the pixel character from the map
	const closedAgentId = chatAgentIds.get(chatId);
	if (closedAgentId !== undefined) {
		broadcast({ type: 'agentClosed', id: closedAgentId });
		chatAgentIds.delete(chatId);
	}

	chatSessions.delete(chatId);
	console.log(`[Chat] Closed chat ${chatId}`);
	broadcast({ type: 'chatClosed', chatId });
}

export function getExistingChatIds(): string[] {
	return Array.from(chatSessions.keys());
}

export function getChatAgentIds(): number[] {
	return Array.from(chatAgentIds.values());
}

export function closeAllChats(broadcast: Broadcast): void {
	for (const chatId of chatSessions.keys()) {
		closeChat(chatId, broadcast);
	}
}
